[package]
name = "Blog"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
serde = "1.0.228"
serde_json = "1.0.145"
web-sys = "0.3.83"
yew = { version = "0.20.0", features = ["csr"] }
